---
- name: Unmount Nokia ISO
  uri:
    url: "https://{{ hostvars[inventory_hostname]['bmc_address'] }}/redfish/v1/Managers/Self/Actions/Oem/AMIVirtualMedia.ConfigureCDInstance/Actions/IsoConfig.UnMount"
    user: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    method: POST
    headers:
      content-type: application/json
      Accept: application/json
    body: {}
    body_format: json
    validate_certs: no
    force_basic_auth: yes
    return_content: yes

- name: Mount Nokia ISO
  uri:
    url: "https://{{ hostvars[inventory_hostname]['bmc_address'] }}/redfish/v1/ManagersSelf/Actions/Oem/AMIVirtualMedia.ConfigureCDInstance/Actions/IsoConfig.Mount"
    user: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    method: POST
    headers:
      content-type: application/json
      Accept: application/json
    body: {"Image": "{{ boot_iso_url }}"}
    body_format: json
    validate_certs: no
    force_basic_auth: yes
    return_content: yes
    status_code: 200
