- name: Check if there is a ISO mounted on the Nokia
  uri:
    url: "https://{{ hostvars[inventory_hostname]['bmc_address'] }}/redfish/v1/Managers/Self/VirtualMedia/CD1"
    user: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    method: GET
    validate_certs: no
    force_basic_auth: yes
    return_content: yes
  register: cd1_contents


- name: Debug boot_iso_url    
  debug:
    var: boot_iso_url

- name: Unmount Nokia ISO
  uri:
    url: "https://{{ hostvars[inventory_hostname]['bmc_address'] }}/redfish/v1/Managers/Self/VirtualMedia/CD1/Actions/VirtualMedia.EjectMedia"
    user: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    method: POST
    headers:
      content-type: application/json
      Accept: application/json
    body: {}
    body_format: json
    validate_certs: no
    force_basic_auth: yes
    return_content: yes
    status_code: 202,204
  when: cd1_contents.json.Inserted | bool == True

- name: Mount Nokia ISO
  uri:
    url: "https://{{ hostvars[inventory_hostname]['bmc_address'] }}/redfish/v1/Managers/Self/VirtualMedia/CD1/Actions/VirtualMedia.InsertMedia"
    user: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    method: POST
    headers:
      content-type: application/json
      Accept: application/json
    body: {"Image": "{{ boot_iso_url }}", "TransferProtocolType":"HTTP"}
    body_format: json
    validate_certs: no
    force_basic_auth: yes
    return_content: yes
    status_code: 202

